### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Renari** [godotessentials/2d-essentials#1]
I'm working on a project and found your addon while implementing my own health component and found your current implementation much more robust than mine.  However I noticed your project is GPL3, would you be willing to offer different terms? Currently my project is closed source and I'm not sure if it will be possible release source for the entire game.

**Comment by s3r0s4pi3ns** [comment]
Hello, @Renari! First and foremost, I want to express my gratitude for utilizing this plugin. Regarding the choice of license, you're absolutely correct. It's possible that the initial selection of that license type was made without clear recollection. As you pointed out, such a license comes with constraints that necessitate users to release their work as open-source.

I've been diligently working on a new release, marked as [v1.3.0](https://github.com/godotessentials/2d-essentials/releases/tag/v1.3.0). This version incorporates the aforementioned changes and also concludes the implementation of the new health overflow functionality. 

If you already have the plugin installed, you'll receive a popup notification the next time you launch the godot editor, prompting you to download and apply the latest update.

I hope you can now use it without any problems, greetings.
