### ISSUE TITLE
get_health_percent() in Health Component

### ISSUE THREAD

**Issue by Lava-er** [godotessentials/2d-essentials#2]
"current_health_percentage": max(1.0, current_health_percentage),

be supposed to

		"current_health_percentage": min(1.0, current_health_percentage),

and this node should be extended from Node instead of Node2D

**Comment by s3r0s4pi3ns** [comment]
Hello @Lava-er, thank you for your feedback. You're absolutely right; that part isn't functioning as expected. I've addressed this issue in the [1.6.2](https://github.com/godotessentials/2d-essentials/releases/tag/v1.6.2).

I apologize for not utilizing pull requests or branches thus far. I typically work solo on this plugin and didn't anticipate it being used in real-world scenarios. I believe it's time for me to take a more concerted approach to this repository.

Cheers!
