### ISSUE TITLE
ProjectileComponent should run on_follow_started(), when beginning to follow a target

### ISSUE THREAD

**Issue by sam-tohru** [godotessentials/2d-essentials#3]
I'm using the ProjectileComponent, when I set a target using: projectile_component.begin_follow_target(new_target)
it doesn't lock onto the target, I need to manually afterwards run: projectile_component.on_follow_started()

so I just do this:
```
	projectile_component.begin_follow_target(new_target)
	projectile_component.on_follow_started()
```
	
I think the Projectiles don't properly emit their signal 'follow_started', and thus never get a direction to the target. 
I tested and found the **follow_target set(value)**, will emit '**follow_stopped**' instead of **'follow_started**'
This is when I'm using the begin_follow_target() function and want it to start following.

I've fixed it on my end by just manually calling **on_follow_started()** inside of **begin_follow_target()** 
(well I call it outside the function as I showed above, but this also fixes it inside the add-on itself):
```
func begin_follow_target(new_target: Node2D) -> void:
	target = new_target
	follow_target = true
	on_follow_started()
```

When not running on_follow_started() projectile either stays still or moves in default direction (and doesn't face target)
![image](https://github.com/godotessentials/2d-essentials/assets/48542828/b2136011-a041-4cfc-903e-207eafa4a6e7)

When I manually run on_follow_started() projectile works as intended, moves & faces direction of target
![image](https://github.com/godotessentials/2d-essentials/assets/48542828/c111753a-c5f1-4f6c-89e0-259ac877fa41)

**Comment by sam-tohru** [comment]
idk if this is a bug or not, but tldr: the signal '**follow_started**' doesn't emit when I set **follow_target**, 
I need to manually run the function **on_follow_started()** when I set a target and it all works good afterwards

**Comment by s3r0s4pi3ns** [comment]
Hi @sam-tohru, taking a quick look I think that the argument I am using when I connect to the on_follow_started() signal is not correct since this signal is actually receiving a Node2D and a float is being used instead.

I'll take a look at it today and try to solve it so it doesn't happen anymore.

Thanks for your patience!
